/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package gestionfichier;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
/**
 *
 * @author SBS
 */
public class Database {
    private static final String URL = "jdbc:oracle:thin:@//localhost:1521/XEPDB1";
    private static final String USER = "SYSTEM";
    private static final String PASS = "12345";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASS);
    }

    public static void creerTable() {
        String sql = "CREATE TABLE fichiers ("
            + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            + "chemin VARCHAR2(500) NOT NULL, "
            + "titre VARCHAR2(255) NOT NULL, "
            + "auteur VARCHAR2(100), "
            + "tags VARCHAR2(500) NOT NULL, "
            + "resume VARCHAR2(1000), "
            + "commentaires VARCHAR2(1000))";

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
            System.out.println("Table créée !");
            System.out.println("succes !!!");
        } catch (SQLException e) {
            System.out.println("Erreur création table : " + e.getMessage());
        }
    }
}
